apiVersion: apps/v1



kind: Deployment



metadata:



 name: task1-deployment



 labels:



  app: tomcat



spec:



 replicas: 3



 strategy:



  type: RollingUpdate



  rollingUpdate:



    maxSurge: "20%"



    maxUnavailable: 0



 selector:



  matchLabels:



   app: tomcat



 template:



  metadata:



   labels:



    app: tomcat



  spec:



   containers:



   - name: tom



     image: manya97/manya_tomcat:0.1

     volumeMounts:

     - name: config-volume

       mountPath: /apache-tomcat-8.0.32/webapps/ROOT

     - name: secret-volume

       mountPath: /apache-tomcat-8.0.32/webapp

     ports:

     - containerPort: 80



   volumes:

     - name: config-volume

       configMap:

         name: cm3

     - name: secret-volume

       secret:

         secretName: my-secret
